name: Download Latest Cloudflared

on:
  # 手动触发
  workflow_dispatch:
  # 每周检查一次新版本 (可选)
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行

jobs:
  download-cloudflared:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Download latest cloudflared
      run: |
        # 创建目录（如果不存在）
        mkdir -p bin
        
        # 下载最新版本的cloudflared
        echo "正在下载 cloudflared..."
        wget -O ./cfd https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        
        # 添加执行权限
        chmod +x ./cfd
        
        # 获取版本信息
        ./cfd --version > ./cfd-version.txt 2>&1 || echo "无法获取版本信息"
        
        # 显示文件信息
        ls -lh ./cfd
    
    - name: Check if file changed
      id: check_changes
      run: |
        # 检查是否有变化
        git add ./cfd ./cfd-version.txt
        if git diff --cached --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "没有检测到 cloudflared 的更新"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "检测到 cloudflared 有更新"
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        # 配置Git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 获取当前时间
        current_time=$(date +'%Y-%m-%d %H:%M:%S')
        
        # 提交更改
        git add ./cfd ./cfd-version.txt
        git commit -m "自动更新 cloudflared 到最新版本 - $current_time"
        
        # 推送更改
        git push
    
